GEMINI_API_KEY=AIzaSyBiLiW0xHuktR5P5KpTNza3uWF0INCiUsc
FIREBASE_API_KEY=AIzaSyAHrx-GSA1kvNDnTG_Bqh5cNvwJeg1XSDI
FIREBASE_DATABASE_URL=https://earn-8b2e8-default-rtdb.firebaseio.com/
DOGRAPAY_API_KEY=dgpy_b4de5cc0eafd0061c38a993ca01c02f0c3a17d92f8d64f961e6844131f08e198
DOGRAPAY_PLATFORM_NAME=Tournament Arena
RAZORPAY_KEY_ID=rzp_live_TAwgHk491SJjq9
